# Generated by Django 3.2.5 on 2021-09-24 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='lesson',
            new_name='tour',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='lesson',
            new_name='tour',
        ),
    ]
