# Generated by Django 3.2.5 on 2021-10-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourdetail',
            name='discount',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tourdetail',
            name='time_start',
            field=models.DateTimeField(null=True),
        ),
    ]
