# Generated by Django 3.2.5 on 2021-11-21 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Views',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='TourDetailViews',
        ),
    ]
