# Generated by Django 3.2.5 on 2021-10-07 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20211006_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='adult',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='children',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='room_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='status',
        ),
    ]
