# Generated by Django 3.2.5 on 2021-10-13 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_auto_20211013_1335'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('tour_detail', 'customer')},
        ),
    ]
