# Generated by Django 3.2.5 on 2021-10-01 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_auto_20211001_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cmt',
            new_name='content',
        ),
    ]
