# Generated by Django 3.2.5 on 2021-10-16 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_user_birthdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together={('phone', 'username')},
        ),
    ]
