# Generated by Django 3.2.5 on 2021-10-07 01:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_auto_20211007_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='booking',
            name='room_price',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Booking processing', 'Booking processing'), ('Booking accepted', 'Booking accepted'), ('Booking canceled', 'Booking canceled')], default='Booking processing', max_length=25),
        ),
    ]
