# Generated by Django 3.2.5 on 2021-12-25 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0004_alter_views_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='content',
        ),
        migrations.AddField(
            model_name='booking',
            name='point_used',
            field=models.IntegerField(null=True),
        ),
    ]
