# Generated by Django 3.2.5 on 2021-10-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0005_auto_20211016_0757'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='decription',
            field=models.TextField(null=True),
        ),
    ]
