# Generated by Django 3.2.5 on 2021-10-20 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0008_alter_blog_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'like'), (1, 'heart'), (2, 'haha'), (3, 'sad'), (4, 'angry')], default=0),
        ),
    ]
